package com.ericgha.docuCloud.converter;

import com.ericgha.docuCloud.dto.CloudUser;
import com.ericgha.docuCloud.dto.FileDto;
import software.amazon.awssdk.services.s3.model.ObjectIdentifier;

import java.util.UUID;

/**
 * Generates filenames for FileStore.  Object names are generated by concatenating joining {@code ObjectId} and
 * {@code fileId} with a {@code .} delimiter (i.e. {ObjectId}.{FileId} ).  The length of each fileKey is 73 characters.
 */
public class ObjectIdentifierGenerator {

    private static final String FORMAT_TEMPLATE = "%1$s.%2$s";

    public static ObjectIdentifier generate(FileDto fileDto, CloudUser cloudUser) {
        return ObjectIdentifierGenerator.generate( fileDto.getFileId(), cloudUser );
    }

    public static ObjectIdentifier generate(UUID fileId, CloudUser cloudUser) {
        var key = String.format(FORMAT_TEMPLATE, cloudUser.getUserId(), fileId );
        return ObjectIdentifier.builder()
                .key( key )
                .build();
    }
}
