version: '3.8'

services:

  postgres-db:
    container_name: docu-cloud-dev-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5435:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
      - ./50000_record_db.sql:/docker-entrypoint-initdb.d/init-50000-record-db.sql:ro

volumes:
  postgres-db-data:
    name: docu-cloud-dev-db_data
    external: false