version: '3.8'

services:

  postgres-db:
    container_name: docu-cloud-dev-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: docu-cloud-dev
    ports:
      - "5435:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data

volumes:
  postgres-db-data:
    name: docu-cloud-dev-db_data
    external: false