package com.ericgha.docuCloud.util.filestore;

import com.ericgha.docuCloud.dto.CloudUser;
import com.ericgha.docuCloud.dto.FileDto;
import com.ericgha.docuCloud.dto.FileViewDto;

/**
 * Generates filenames for FileStore.  Object names are generated by concatenating joining {@code ObjectId} and
 * {@code fileId} with a {@code .} delimiter (i.e. {ObjectId}.{FileId} ).  The length of each fileKey is 73 characters.
 */
public class FileKeyGenerator {

    private static final String FORMAT_TEMPLATE = "%1$s.%2$s";

    private FileKeyGenerator() throws  IllegalAccessException {
        throw new IllegalAccessException("Do not instantiate.");
    }

    public static String generate(CloudUser cloudUser, FileDto fileDto) {
        return String.format(FORMAT_TEMPLATE, cloudUser.getUserId(), fileDto.getFileId() );
    }

    public static String generate(CloudUser cloudUser, FileViewDto fileViewDto) {
        return String.format(FORMAT_TEMPLATE, cloudUser.getUserId(), fileViewDto.getFileId() );
    }



}
